#!/usr/bin/tcsh
clear
if ($3 == "X-c" ) then
  echo "   a  b  c  d  e  f  g  h\n"
  cat memboard | sed 'N;N;N;N;N;N;N;s/\n/  /g;' | sed '=;' | sed 'N;s/\n/  /;G' | ./sed_script
  echo "\n-------------------------\n"
endif
cat memboard  | sed "$1bL;$2bL;s/[A-X]/?/;:L;"  > f3
echo "   a  b  c  d  e  f  g  h\n"
cat f3 | sed 'N;N;N;N;N;N;N;s/\n/  /g;' | sed '=;' | sed 'N;s/\n/  /;G' | ./sed_script | grep --color -e "[^1-6a-h_?]" -e "^"
echo 
set x = `cat f3 | sed '/?/d;/_/d;' | uniq -c | sed -n '$='`
if ( $x == 1 ) cat memboard | sed "$1s/./_/;$2s/./_/;" > f3
exit $x
