#!/usr/bin/tcsh
while 1
  while 1
    echo -n "\nEnter your choice: "
    set ch = $<
    if ( $ch =~ [a-h][1-6] ) break
    echo "Invalid choice. Please try again."
  end
  set x = `echo $ch | sed 'y/abcdefgh/12345678/;s/\(.\)\(.\)/8 * \( \2 - 1 \) + \1/' | xargs expr`
  ( expr $x != $1 && expr 1 + `cat memboard | sed -n "$x s/[A-X]/1/;$x p"` ) >& /dev/null && exit $x
  echo "That place is already revealed. Please try again."
end
    
