#!/usr/bin/tcsh
echo -n ABCDEFGHIJKLMNOPQRSTUVWX | sed 's/[A-X]/&\n/g' | tee memboard | tr A-Z a-z > lets; cat memboard >> lets
set array = ( `cat lets` )
set symbol_array = ( `sort -R symbols | head -24` )
echo sed \'"y/$array[25-48]/$symbol_array/"\' > sed_script
cat lets | sort -R | tr "a-z" "A-Z" > memboard
@ choice1 = 50
@ choice2 = 50
@ cnt = 0
while (1)
  ./displayboard $choice1 $choice2 X$1
  if ( $? == 1 ) then
  expr 1 `cat f3 | sed -n 's/[A-X]/=/p;'` >&/dev/null && echo \\nCongratulations\! Finished in $cnt moves.\\n && exit
mv -f f3 memboard
  endif
  ./getchoice 50
  set choice1 = $?  
  ./displayboard $choice1 50 X$1
  ./getchoice $choice1
  set choice2 = $?
  @ cnt++
end
#:L;$\!N;s/\(_\)*\n//;tL;$='
