#!/bin/tcsh
while 1
	while 1
		echo -n "\nEnter your choice: "
		set ch = "$<"
		echo $ch | grep -o '.' | grep -n '[a-h]' | grep -q '1'  && \
		echo $ch | grep -o '.' | grep -n '[1-6]' | grep -q '2' && break
		echo "Invalid choice. Please try again."
	end
	echo $ch | grep -o '.' | sort | tr 'a-h\n' '1-8+' | grep -o '.' | tr '\n' ' ' | xargs echo '8 \* ' | expr `grep '*'` -8 > pos
	set x = `head -1 pos`
	if ( $x != $1 ) cat memboard | tr ',' '\n' | grep -nv '_' | grep -q "^$x\:" && exit $x
	echo "That place is already revealed. Please try again."
end
