#!/bin/tcsh
echo ABCDEFGHIJKLMNOPQRSTUVWX | grep -no "[A-X]" | tr -d "0-9" | tee letters | tr "A-Z" "a-z" >> letters
sort -R letters | tr "\n:a-z" ", A-Z" > memboard
@ x = 0
@ y = 0
set z = 0
while ( 1 )
./displayboard $x $y $1
if ( x$? == x2 ) then
cat memboard | tr `head -1 chosen | tail -c2 | head -c1` "_" > board_temp 
cat board_temp > memboard
grep -q ' _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,' memboard && echo "Congratulations! Finished in $z moves.\n" && exit
endif
./getchoice 0
set x = $?
./displayboard $x 0 $1
./getchoice $x
set y = $?
@ z++ 
end
